export const locationNames = [
	"Adi Udupi",
	"Ambagilu",
	"Bannanje",
	"Beedinagudde",
	"Brahmavar",
	"End Point",
	"Hampankatta",
	"Hoode",
	"Kalsanka",
	"Karkala",
	"Kaup",
	"KMC Manipal",
	"Kodialbail",
	"Koteshwar",
	"Kukkikatte",
	"Kunjal",
	"Kunjibettu",
	"Malpe",
	"Manipal",
	"Mannagudda",
	"Marnabail",
	"Moodabidri",
	"Padubidri",
	"Parkala",
	"Perampalli",
	"Santhekatte",
	"Shirva",
	"Uchila",
	"Udupi",
	"Vamanjoor",
	"Yeyyadi",
	"End Point",
	"Tiger Circle",
	"MIT Manipal",
	"Madhav Nagar",
	"Adarsha Nagar",
	"Eshwar Nagar",
	"Syndicate Circle",
	"Green Park",
	"Ananth Nagar",
	"Vidyaratna Nagar",
	"Industrial Area",
];
